# Generated by Django 4.1.7 on 2023-05-20 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=15)),
                ('user_name', models.CharField(max_length=40)),
                ('user_email', models.CharField(max_length=40)),
                ('user_mobile', models.CharField(max_length=10)),
                ('user_password', models.CharField(max_length=40)),
                ('user_role', models.CharField(default=1, max_length=1)),
            ],
            options={
                'ordering': ['user_id'],
            },
        ),
    ]
