# Generated by Django 4.1.7 on 2023-05-21 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microapp', '0003_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=15)),
                ('book_id', models.CharField(max_length=15)),
                ('order_date', models.DateField(null=True)),
                ('delivery_date', models.DateField(null=True)),
                ('user_id', models.CharField(max_length=15)),
                ('contact_no', models.CharField(max_length=10)),
                ('order_status', models.CharField(choices=[('0', 'pending'), ('2', 'Confirmed'), ('3', 'Rejected'), ('4', 'Rejected'), ('6', 'Delivered'), ('7', 'Delivery Failed'), ('8', 'Cancelled')], default='0', max_length=2)),
                ('item_count', models.IntegerField(default=0)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('total_discount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('tax', models.DecimalField(decimal_places=2, max_digits=6)),
                ('net_amount', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
            options={
                'ordering': ['order_id'],
            },
        ),
    ]
