# Generated by Django 4.1.7 on 2023-05-21 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('microapp', '0004_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
    ]
